export const TRANSFER_ACTION = 'transfer'
export const DELEGATE_BW_ACTION = 'delegatebw'
export const UNDELEGATE_BW_ACTION = 'undelegatebw'
export const VOTE_PRODUCER_ACTION = 'voteproducer'
export const BUY_RAM_ACTION = 'buyram'
export const BUY_RAM_BYTES_ACTION = 'buyrambyes'
export const SELL_RAM_ACTION = 'sellram'
